I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 70, in script call
    call Game_Over
  File "game/script.rpy", line 373, in script
    jump main_menu
ScriptError: could not find label 'main_menu'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 70, in script call
    call Game_Over
  File "game/script.rpy", line 373, in script
    jump main_menu
  File "/home/fuvity/Desktop/renpy-6.99.1-sdk/renpy/ast.py", line 1480, in execute
    rv = renpy.game.script.lookup(target)
  File "/home/fuvity/Desktop/renpy-6.99.1-sdk/renpy/script.py", line 602, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'main_menu'.

Linux-3.16.0-33-generic-x86_64-with-debian-jessie-sid
Ren'Py 6.99.1.329
Iluminati Cthullu 0.0
